### ISSUE TITLE
some

### ISSUE THREAD

**Issue by canliture** [liuyubobobo/Play-with-Algorithms#18]
https://github.com/liuyubobobo/Play-with-Algorithms/blob/bd14f6c2299025cd9178530d3f641c16a0bc0f83/07-Graph-Basics/Course%20Code%20(C%2B%2B)/02-Graph-Representation/DenseGraph.h#L20

Some IDEs can be report errors where ">>" in "vector<vector&lt;type&gt;>". And if users use those IDEs, they must change "vector<vector&lt;type&gt;>" into "vector<vector&lt;type&gt; >".

**Comment by liuyubobobo** [comment]
It's not about IDE, it's about compiler. Modern C++ compilers(C++11 or above) doesn't have this issue as far as I know. Since the C++ codes in this repo are based on C++11, I will not make a change because of the compatibility (which seems will be a limitless work) 

Yes, if you use like C++98, you need to change it into "vector<vector<bool> >". A space is needed between the two '>' characters to make a difference from the operator ">>".

Actually, it's more like a bug, in my opinion, for old version C++ compilers fail to distinguish this two situations :-)
